### ISSUE TITLE
No blur in context menu under KDE Plasma with Force Blur Script

### ISSUE THREAD

**Issue by sinkuroi** [manilarome/blurredfox#42]
Hi,

I'm running Firefox 81.0. All blur effects appear to be working, apart from the context menu.

![Screenshot_20200928_155825](https://user-images.githubusercontent.com/40974679/94449055-8fdf3880-01a3-11eb-8951-d3f5e4c8a61b.png)

As you can see it's quite difficult to read without the blur effect. I'm running KDE Plasma 5.19.5. I've added firefox to Force Blur with no change. I'll note that the context menu blur in the rest of my DE works fine, though I'm unsure if they are related in any way. In the meantime I just commented out the context menu line to get the default context menu appearance. 

Any help would be appreciated!

**Comment by eromatiya** [comment]
This is more of a compositor issue, not blurredfox. As you can see, there's a blur effect in my context menu and it's provided by picom:

![1](https://user-images.githubusercontent.com/40349590/94493934-89db6d00-0220-11eb-9307-15927e9445c6.png)

I also cannot test it because I don't use KDE Plasma. Although I'll probably just download and install an ISO into a VM. But yeah, right now I don't have a way to test this. Just experiment with Force Blur or something.

**Comment by thegrasshopper104** [comment]
It's not working for me either

**Comment by eromatiya** [comment]
I can't really do anything about this because it's a compositor thing. Best thing to do is to ask the Force Blur dev to support `popup_menu` window type blurring like picom.
