### ISSUE TITLE
Firefox user directory fix suggestion

### ISSUE THREAD

**Issue by Cognomines** [manilarome/blurredfox#7]
```bash
diff --git a/install.sh b/install.sh
index 8130ab1..85f2a2a 100755
--- a/install.sh
+++ b/install.sh
@@ -45,7 +45,7 @@ EOF
 }
 
 
-FF_USER_DIRECTORY="$(find "${HOME}/.mozilla/firefox/"  -maxdepth 1 -type d -regextype egrep -regex '.*[a-zA-Z0-9]+.default-release')"
+FF_USER_DIRECTORY="$(find "${HOME}/.mozilla/firefox/"  -maxdepth 1 -type d -regextype egrep -regex '.*[a-zA-Z0-9]+.default-(release|default)')"
 
 if [[ -n $FF_USER_DIRECTORY ]];
 then
```
I encountered an issue on gentoo linux. 

```bash
~/.mozilla/firefox $ ls
installs.ini  jt3khmjq.default-default  pk9k6luc.default  profiles.ini
~/.mozilla/firefox $
```

**Comment by manilarome** [comment]
Thank you, kind sir! https://github.com/manilarome/blurredfox/commit/2e25f384b5e1bee2fc9b4674813a385028638f50

**Comment by yoruba-codigy** [comment]
I Know This Is Closed, But Just Another Suggestion Similar To Cognomine's

`FF_USER_DIRECTORY="$(find "${HOME}/.mozilla/firefox/"  -maxdepth 1 -type d -regextype egrep -regex '.*[a-zA-Z0-9]+.default-(release|default)')"
`

I Encountered An Issue On Kali Linux

```
~/.mozilla/firefox
$ ls
 7maf7y2f.default-esr/  'Crash Reports'/   gj1haqss.default/  'Pending Pings'/   installs.ini   profiles.ini
~/.mozilla/firefox
$
```

**Comment by manilarome** [comment]
Thanks @yoruba-codigy! Will implement it.

**Comment by podiki** [comment]
I also had some issues with profile finding, could be because of using [profile sync daemon](https://wiki.archlinux.org/index.php/Profile-sync-daemon). This means I have a symlink instead of a straight directory. Mine also didn't have `-default` or anything like that after `.default`, not sure if that is because of this as well. So I needed to remove that as well as the `type` option (since it is a symlink):

`FF_USER_DIRECTORY="$(find "${HOME}/.mozilla/firefox/" -maxdepth 1 -regextype egrep -regex '.*[a-zA-Z0-9]+.default')"`

And then for the `chrome` directory I needed a slash added from the above variable:

`CHROME_DIRECTORY="$(find "$FF_USER_DIRECTORY/" -maxdepth 1 -type d -name 'chrome')"`

Not sure how you want to use that for the general case, but in case anyone else runs into this. And thanks for the very nice looking theme!
